"""empty message

Revision ID: fcd508371349
Revises: None
Create Date: 2018-05-18 11:14:55.254697

"""

# revision identifiers, used by Alembic.
revision = 'fcd508371349'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software')
    op.drop_table('software_key')
    op.drop_table('service')
    op.drop_table('wol_computer')
    op.drop_table('software_user')
    op.drop_table('user_license')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_license',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('software_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('software_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['software_id'], [u'software.id'], name=u'user_license_ibfk_2'),
    sa.ForeignKeyConstraint(['software_user_id'], [u'software_user.id'], name=u'user_license_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('software_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('wol_computer',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('computer', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('service',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('software_key',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('serial', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('common', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('software',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('software_name', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('downloadlink', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('license', mysql.TEXT(), nullable=True),
    sa.Column('license_expires', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('license_expiry_date', mysql.DATETIME(), nullable=True),
    sa.Column('license_renewal_date', mysql.DATETIME(), nullable=True),
    sa.Column('owner', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('explicit_approval_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
